import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Stock Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="content">
          {children}
        </div>
        <footer className="footer">
          <p>&copy; {new Date().getFullYear()} LWJ StockManager. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
